#
#  ██╗██╗░░░░░██╗░░░░░███████╗░██████╗░░█████╗░██╗░░░░░░░░░░░██╗████████╗███████╗███╗░░░███╗░██████╗██╗
#    ██║██║░░░░░██║░░░░░██╔════╝██╔════╝░██╔══██╗██║░░░░░░░░░░░██║╚══██╔══╝██╔════╝████╗░████║██╔════╝╚═╝
#    ██║██║░░░░░██║░░░░░█████╗░░██║░░██╗░███████║██║░░░░░█████╗██║░░░██║░░░█████╗░░██╔████╔██║╚█████╗░░░░
#    ██║██║░░░░░██║░░░░░██╔══╝░░██║░░╚██╗██╔══██║██║░░░░░╚════╝██║░░░██║░░░██╔══╝░░██║╚██╔╝██║░╚═══██╗░░░
#    ██║███████╗███████╗███████╗╚██████╔╝██║░░██║███████╗░░░░░░██║░░░██║░░░███████╗██║░╚═╝░██║██████╔╝██╗
#    ╚═╝╚══════╝╚══════╝╚══════╝░╚═════╝░╚═╝░░╚═╝╚══════╝░░░░░░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝╚═════╝░╚═╝
max_bytes: 2048 # The recommended value is 2048
max_nbt_size_kb: 100 # Adjust as you see fit
