#
#  ██╗██╗░░░░░██╗░░░░░███████╗░██████╗░░█████╗░██╗░░░░░░░░░░░██╗████████╗███████╗███╗░░░███╗░██████╗██╗
#    ██║██║░░░░░██║░░░░░██╔════╝██╔════╝░██╔══██╗██║░░░░░░░░░░░██║╚══██╔══╝██╔════╝████╗░████║██╔════╝╚═╝
#    ██║██║░░░░░██║░░░░░█████╗░░██║░░██╗░███████║██║░░░░░█████╗██║░░░██║░░░█████╗░░██╔████╔██║╚█████╗░░░░
#    ██║██║░░░░░██║░░░░░██╔══╝░░██║░░╚██╗██╔══██║██║░░░░░╚════╝██║░░░██║░░░██╔══╝░░██║╚██╔╝██║░╚═══██╗░░░
#    ██║███████╗███████╗███████╗╚██████╔╝██║░░██║███████╗░░░░░░██║░░░██║░░░███████╗██║░╚═╝░██║██████╔╝██╗
#    ╚═╝╚══════╝╚══════╝╚══════╝░╚═════╝░╚═╝░░╚═╝╚══════╝░░░░░░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝╚═════╝░╚═╝
max_bytes: 2048 # Рекомендуемое значение - 2048
max_nbt_size_kb: 100 # Регулируйте на своё усмотрение
