#
#  ██╗██╗░░░░░██╗░░░░░███████╗░██████╗░░█████╗░██╗░░░░░░░░░░░██╗████████╗███████╗███╗░░░███╗░██████╗██╗
#    ██║██║░░░░░██║░░░░░██╔════╝██╔════╝░██╔══██╗██║░░░░░░░░░░░██║╚══██╔══╝██╔════╝████╗░████║██╔════╝╚═╝
#    ██║██║░░░░░██║░░░░░█████╗░░██║░░██╗░███████║██║░░░░░█████╗██║░░░██║░░░█████╗░░██╔████╔██║╚█████╗░░░░
#    ██║██║░░░░░██║░░░░░██╔══╝░░██║░░╚██╗██╔══██║██║░░░░░╚════╝██║░░░██║░░░██╔══╝░░██║╚██╔╝██║░╚═══██╗░░░
#    ██║███████╗███████╗███████╗╚██████╔╝██║░░██║███████╗░░░░░░██║░░░██║░░░███████╗██║░╚═╝░██║██████╔╝██╗
#    ╚═╝╚══════╝╚══════╝╚══════╝░╚═════╝░╚═╝░░╚═╝╚══════╝░░░░░░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝╚═════╝░╚═╝
max_bytes: 2048 # Рекомендуемое значение - 2048
